### ISSUE TITLE
Azure dpeloyment failure: Cannot find User with name 10032000E21251C3

### ISSUE THREAD

**Issue by abulgatz** [nicolonsky/ModernWorkplaceConcierge#84] opened 2021-09-23 19:30 UTC
- Resource: `ModernWorkplaceConciergeSite/web`
- Type: `Microsoft.Web/sites/sourcecontrols`
- Status Message:

```json
{
    "status": "Failed",
    "error": {
        "code": "NotFound",
        "message": "Cannot find User with name 10032000E21251C3.",
        "details": [
            {
                "message": "Cannot find User with name 10032000E21251C3."
            },
            {
                "code": "NotFound"
            },
            {}
        ]
    }
}
```

**Comment by abulgatz** [comment] 2021-09-23 20:20
This appears it might be an issue with the `tree/master` at the end of the **Repo Url** when deploying.

**Comment by nicolonsky** [comment] 2022-05-20 09:43
Duplicate of https://github.com/nicolonsky/ModernWorkplaceConcierge/issues/88 / merged

**Closed as completed by nicolonsky** 2022-05-20 09:43 UTC
