### ISSUE TITLE
Trello import takes forever ... nothing seems to happen

### ISSUE THREAD

**Issue by abrbon** [nicolonsky/ModernWorkplaceConcierge#77] opened 2021-02-19 19:57 UTC
Hi,
Tried to import a small Json file about 622kb but it seems to take forever.
All i can see is "SignalR connection established, connection ID: xxxxx" and the Import icon keep showing the spinning circle.
I have been waiting now for about 20min and still nothing shows up in notifications.

I only see the 'buckets' created in MS Planner but nothing else.

**Comment by developingkatie** [comment] 2021-04-14 12:55
did you manage to sort this? At work we've cloned the code to put our own interface on it but we're getting the exact same symptoms and can't understand why

**Comment by abrbon** [comment] 2021-04-14 13:05
No have not found solution but we have manually put our data over to MS Planner.
Took to long for a response. Fortunately it was not a lot of data and took about a day to transfer it manually

**Comment by developingkatie** [comment] 2021-04-14 14:33
yeah we're reluctant to do anything manually as one of our users has several boards to import, every time we think we have this working it breaks again!

**Comment by nicolonsky** [comment] 2021-04-22 06:08
Duplicate of https://github.com/nicolonsky/ModernWorkplaceConcierge/issues/75

**Closed as completed** 2022-07-11 10:32 UTC
